In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
#array and list diff -> array has same data type

In [4]:
sample_list = [1,2,3,4,5,6]
print(sample_list*2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [6]:
sample_numpy_array = ([1,2,3,4,5,6])
sample_numpy_array = sample_numpy_array*2
sample_numpy_array

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [9]:
a = [[1,2,3], [4,5,6],[7,8,9]]
a = np.array(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a = [[1,2,3], [4,5,6],[7,8,9]]
a = np.array(a)
print(a[0][1])

2


In [11]:
#Creating matrix with random numbers using np.random.randint(0,10,(3,3)) -> 0,10 is the range, (3,3) is the dimension
b = np.random.randint(0,10,(3,3))
print(b)

[[7 4 7]
 [4 2 1]
 [8 3 6]]


In [12]:
b = np.random.randint(0,10,(3,4))
print(b)

[[4 3 0 4]
 [9 5 6 0]
 [8 9 5 2]]


In [13]:
k = np.random.seed(0)
k1 = np.random.randint(0,10,(3,3))
k1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [16]:
k3 = np.zeros((3,4), dtype=int)
k3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
k4 = np.zeros((3,9), dtype=int)
k4

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
k5 = np.ones((3,9), dtype=int)
k5

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [21]:
k7 = np.identity(5, dtype=int)
k7

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
k8 = np.full((3,4), 7)
k8

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [27]:
matrix1 = np.array([1,2,3,4,5])
matrix2 = np.array([6,7,8,9,10])
matrix3 = np.concatenate([matrix1, matrix2], axis = 0)
matrix3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])